pub const MASSIVE_SEED: &[&str] = &[
    "el", "la", "los", "las", "un", "una", "unos", "unas", "de", "del", "que", "qué", "y", "o", "a", "ante", "bajo", "con", "contra", "en", "entre", "hacia", "hasta", "para", "por", "según", "sin", "sobre", "tras",
    "me", "te", "se", "nos", "os", "lo", "los", "la", "las", "le", "les", "mi", "tu", "su", "nuestro", "vuestro", "mío", "tuyo", "suyo", "yo", "tú", "él", "ella", "nosotros", "ellos", "usted", "ustedes",
    "este", "esta", "esto", "ese", "esa", "eso", "aquel", "aquella", "aquello", "aquí", "ahí", "allí", "acá", "allá",
    "quién", "quiénes", "cuál", "cuáles", "cuánto", "cuánta", "cuántos", "cuántas", "cómo", "cuándo", "dónde", "por qué", "qué",
    "no", "sí", "también", "tampoco", "siempre", "nunca", "jamás", "quizás", "tal vez", "acaso", "aún", "todavía", "ya", "ahora", "antes", "después", "luego", "hoy", "ayer", "mañana", "pronto", "tarde", "bien", "mal", "muy", "tan", "más", "menos", "así", "apenas", "casi", "solo", "solamente", "incluso", "inclusive",
    "todo", "nada", "algo", "alguien", "nadie", "alguno", "cada", "otro", "mismo", "tanto", "varios", "muchos", "pocos", "bastante", "demasiado",
    "bueno", "malo", "grande", "pequeño", "mejor", "peor", "mayor", "menor", "nuevo", "viejo", "primero", "último", "alto", "bajo", "largo", "corto", "ancho", "estrecho", "fuerte", "débil", "fácil", "difícil", "posible", "imposible", "libre", "ocupado", "claro", "oscuro", "ligero", "pesado", "rápido", "lento", "caliente", "frío", "joven", "anciano",
    "ser", "estar", "haber", "hacer", "tener", "poder", "querer", "deber", "saber", "decir", "ir", "venir", "ver", "mirar", "oír", "escuchar", "dar", "tomar", "poner", "salir", "llegar", "llevar", "traer", "comer", "beber", "dormir", "hablar", "pensar", "sentir", "creer", "conocer", "entender", "comprender", "aprender", "enseñar", "ayudar", "buscar", "encontrar", "perder", "ganar", "empezar", "comenzar", "acabar", "terminar", "esperar", "necesitar", "pedir", "llamar", "recordar", "olvidar", "vivir", "morir", "parecer", "pasar", "quedar", "seguir", "dejar", "tratar", "intentar", "lograr", "conseguir", "analizar", "sentir",
    "persona", "hombre", "mujer", "niño", "niña", "gente", "vida", "mundo", "tiempo", "momento", "lugar", "espacio", "día", "noche", "mañana", "tarde", "semana", "mes", "año", "hora", "parte", "lado", "manera", "forma", "tipo", "clase", "modo", "punto", "tema", "asunto", "cosa", "objeto", "agua", "fuego", "aire", "tierra", "luz", "sol", "luna", "cielo", "mar", "bosque", "montaña", "flor", "animal", "casa", "ciudad", "pueblo", "país", "calle", "camino", "puerta", "ventana", "pared", "muro", "suelo", "techo", "mesa", "silla", "cama", "libro", "palabra", "nombre", "letra", "número", "página", "historia", "verdad", "mentira", "razón", "sentido", "idea", "pensamiento", "mente", "corazón", "cuerpo", "mano", "pie", "cabeza", "ojo", "cara", "boca", "voz", "sonido", "música", "arte", "diseño", "trabajo", "escuela", "familia", "amigo", "amor", "odio", "miedo", "paz", "guerra", "poder", "fuerza"
];
